### ISSUE TITLE
(println "string") is not printing any output on the browser

### ISSUE THREAD

**Issue by woosley** [roryk/clojupyter#15]
```
In [12]: (println "string")
Out[12]: nil
```

only the return value of the expression is printed, is this expected? how can I get output printed?

**Comment by roryk** [comment]
Hi @woosley,

Thanks and sorry for the issue. It is expected behavior, but not optimal behavior. Right now clojupyter is set up to evaluate the function and return the results; the stdout is sent along in a different message and right now we just drop the message on the floor instead of displaying it. That is totally doable, it just not implemented.

**Comment by roryk** [comment]
Thanks @woosley,

This is fixed now, sorry for the delay in getting to it. Thanks!

**Comment by woosley** [comment]
thanks! @roryk

**Comment by pdenno** [comment]
Sorry I wasn't able to help. I was on vacation and away from my email.

**Comment by roryk** [comment]
No worries Peter, hope you had a great time on your vacation!

**Comment by woosley** [comment]
actually this issue does not seem to be fix, I still can not get stdout in brower.

**Comment by roryk** [comment]
Hi @woosley,

You might be loading the old `ipython-clojure` executable instead of the renamed clojupyter one. If you nuke your ~/.ipython/kernels/clojure directory and reinstall it should be all good.

If you are on OSX you'll have to also get rid of the kernel cache:

https://github.com/roryk/clojupyter#removing-the-stale-osx-kernel-cache

**Comment by woosley** [comment]
indeed! thanks!
